- name: fix
  hosts: localhost
  vars:
    var_password_pam_minlen: 15
    var_password_pam_dcredit: -1
    var_password_pam_lcredit: -1
    var_password_pam_ocredit: -1
    var_password_pam_ucredit: -1
  tasks:
  - name: Create a password flag file in /etc/portage/package.use
    ansible.builtin.file:
      path: /etc/portage/package.use/pambase
      state: touch
      modification_time: preserve
      access_time: preserve
  - name: Add pwquality and -passwdqc flag
    ansible.builtin.lineinfile:
      path: /etc/portage/package.use/pambase
      line: 'sys-auth/pambase pwquality -passwdqc'
    register: compile_flags
  - name: Emerge pambase
    community.general.portage:
      package: pambase
      state: present
      noreplace: false
    when: compile_flags.changed
  - name: Ensure pam is correctly configured
    ansible.builtin.lineinfile:
      path: /etc/pam.d/system-auth
      state: present
      regexp: '^password[\s]*required[\s]*pam_pwquality.so'
      state: present
      line: 'password    required    pam_pwquality.so'
  - name: Create a pwquality.conf file
    ansible.builtin.file:
      path: /etc/security/pwquality.conf
      state: touch
      modification_time: preserve
      access_time: preserve
  - name: Ensure passwords with minimum of {{ var_password_pam_minlen }} characters
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      line: 'minlen = {{ var_password_pam_minlen }} '
  - name: Ensure passwords with minimum of {{ var_password_pam_dcredit }} digit character
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      line: 'ocredit = {{ var_password_pam_dcredit }}'
  - name: Ensure passwords with minimum of {{ var_password_pam_lcredit }} lower case character
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      line: 'dcredit = {{ var_password_pam_lcredit }}'
  - name: Ensure passwords with minimum of {{ var_password_pam_ocredit }} special character
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      line: 'ucredit = {{ var_password_pam_ocredit }}'
  - name: Ensure passwords with minimum of {{ var_password_pam_ucredit }} upper case character
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      line: 'lcredit = {{ var_password_pam_ucredit }}'
