- name: fix
  hosts: localhost
  vars:
    var_password_pam_minlen: 15
    var_password_pam_dcredit: -1
    var_password_pam_lcredit: -1
    var_password_pam_ocredit: -1
    var_password_pam_ucredit: -1
    var_password_pam_unix_remember: 2
    var_accounts_tmout: 600
    var_sudo_umask: '0077'
    var_accounts_user_umask: '077'
    var_accounts_passwords_pam_faillock_deny: 3
    var_accounts_passwords_pam_faillock_fail_interval: 900
  tasks:
  - name: Add pwquality and -passwdqc flag
    ansible.builtin.lineinfile:
      path: /etc/portage/package.use/pambase
      line: sys-auth/pambase pwquality -passwdqc
      create: true
    register: compile_flags

  - name: Emerge pambase
    community.general.portage:
      package: pambase
      state: present
      noreplace: false
    when: compile_flags.changed

  - name: Ensure pam is correctly configured to use pwquality.so
    ansible.builtin.lineinfile:
      path: /etc/pam.d/system-auth
      state: present
      regexp: ^password[\s]+required[\s]+pam_pwquality.so
      state: present
      line: password    required    pam_pwquality.so

  - name: Ensure passwords with minimum of {{ var_password_pam_minlen }} characters
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      create: true
      line: minlen = {{ var_password_pam_minlen }}

  - name: Ensure passwords with minimum of {{ var_password_pam_dcredit }} digit character
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      line: ocredit = {{ var_password_pam_dcredit }}

  - name: Ensure passwords with minimum of {{ var_password_pam_lcredit }} lower case character
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      line: dcredit = {{ var_password_pam_lcredit }}

  - name: Ensure passwords with minimum of {{ var_password_pam_ocredit }} special character
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      line: ucredit = {{ var_password_pam_ocredit }}

  - name: Ensure passwords with minimum of {{ var_password_pam_ucredit }} upper case character
    ansible.builtin.lineinfile:
      path: /etc/security/pwquality.conf
      line: lcredit = {{ var_password_pam_ucredit }}

  - name: Ensure pam is correctly configured to use pwhistory.so
    ansible.builtin.lineinfile:
      path: /etc/pam.d/system-auth
      state: present
      regexp: ^password[\s]+required[\s]+pam_pwhistory.so
      state: present
      line: password    required    pam_pwhistory.so

  - name: Ensure passwords different by the last {{ var_password_pam_unix_remember }}
    ansible.builtin.lineinfile:
      path: /etc/security/pwhistory.conf
      create: true
      line: remember = {{ var_password_pam_unix_remember }}

  - name: Set interactive session timeout at {{ var_accounts_tmout }} s
    ansible.builtin.lineinfile:
      path: /etc/profile.d/tmout.sh
      create: true
      regexp: (?:typeset|declare)[\s]+-xr[\s]+TMOUT=([\w$]+).*$
      line: typeset -xr TMOUT={{ var_accounts_tmout }}

  - name: Ensure default umask configuration in /etc/bashrc
    ansible.builtin.lineinfile:
      path: /etc/bash/bashrc.d/umask.sh
      line: umask {{ var_accounts_user_umask }}
      create: true

  - name: Ensure default umask configuration in /etc/profile
    ansible.builtin.lineinfile:
      path: /etc/profile
      line: 'umask {{ var_accounts_user_umask }}'

  - name: Ensure default umask configuration in /etc/login.defs
    block:
      - name: Remove previous UMASK configuration
        ansible.builtin.lineinfile:
          path: /etc/login.defs
          regexp: '^(\s*)UMASK\s+.*'
          state: absent

      - name: Add a new UMASK configuration
        ansible.builtin.lineinfile:
          path: /etc/login.defs
          line: 'UMASK {{ var_accounts_user_umask }}'

  - name: Ensure default umask configuration in /etc/bash/bashrc
    ansible.builtin.lineinfile:
      path: /etc/bash/bashrc
      line: umask {{ var_accounts_user_umask }}

  - name: Set env_reset sudo flag
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/anssi_falgs
      line: Defaults  env_reset
      create: true

  - name: Set ignore_dot sudo flag
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/anssi_falgs
      line: Defaults  ignore_dot

  - name: Set use_pty sudo flag
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/anssi_falgs
      line: Defaults  use_pty

  - name: Set noexec sudo flag
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/anssi_falgs
      line: Defaults  noexec

  - name: Set require_tty sudo flag
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/anssi_falgs
      line: Defaults  requiretty

  - name: Set umask sudo flag to {{ var_accounts_sudo_umask }}
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/anssi_falgs
      line: Defaults  umask={{ var_sudo_umask }}

  - name: Set /etc/shadow file permissions
    ansible.builtin.file:
      path: /etc/shadow
      state: touch
      mode: '0000'

  - name: Set /etc/gshadow file permissions
    ansible.builtin.file:
      path: /etc/gshadow
      state: touch
      mode: '0000'

  - name: Set /etc/shadow file ownership
    ansible.builtin.file:
      path: /etc/shadow
      state: touch
      owner: root

  - name: Set /etc/gshadow file ownership
    ansible.builtin.file:
      path: /etc/gshadow
      state: touch
      owner: root

  - name: Set /etc/shadow file group
    ansible.builtin.file:
      path: /etc/shadow
      state: touch
      group: 'root'

  - name: Set /etc/gshadow file group
    ansible.builtin.file:
      path: /etc/gshadow
      state: touch
      group: 'root'
